export type ModuleCategory = 'normas_internas' | 'academia_transporte' | 'guia_sensivel';

export type NormaType = 'proibicao' | 'alerta' | 'recomendado' | 'diretriz';

export interface ManualNorma {
  id: string;
  moduleId: ModuleCategory;
  moduleTitle?: string;
  sectionNumber?: string;
  sectionTitle?: string;
  title: string;
  type: NormaType;
  summary: string;
  details: string[];
  tags: string[];
  order?: number;
  createdAt?: string;
  updatedAt?: string;
  updatedBy?: string;
}

export const MODULE_METADATA: Record<
  ModuleCategory,
  {
    title: string;
    description: string;
    defaultSectionNumber: string;
    icon: string;
  }
> = {
  normas_internas: {
    title: 'Módulo 1: Normas Internas e Rotina do Integral',
    description: 'Direitos, deveres, vestuário, proibições, rádio frequência 2, refeitório, parque, culinária e lição de casa',
    defaultSectionNumber: '1.0',
    icon: 'Award',
  },
  academia_transporte: {
    title: 'Módulo 2: Academia, Transporte e Locais Parceiros',
    description: 'Deslocamento Portaria B/C, 10 regras da academia, proibição de chinelo no colégio e segurança no portão',
    defaultSectionNumber: '2.0',
    icon: 'Bus',
  },
  guia_sensivel: {
    title: 'Módulo 3: Guia de Abordagem Sensível e Respeitosa',
    description: 'Comunicação assertiva, não gritar, não puxar, paciência e mediação em 3 passos (Coord. Fernando Veiga)',
    defaultSectionNumber: '3.0',
    icon: 'HeartHandshake',
  },
};

export const INITIAL_MANUAL_NORMAS: ManualNorma[] = [
  // ==========================================
  // MÓDULO 1: NORMAS INTERNAS E ROTINA DO INTEGRAL
  // ==========================================
  {
    id: 'norma_objetivos_metas',
    moduleId: 'normas_internas',
    moduleTitle: 'Módulo 1: Normas Internas e Rotina do Integral',
    sectionNumber: 'Objetivos',
    sectionTitle: 'Metas e Proposta do Integral',
    title: 'Objetivos e Metas do Programa de Integral',
    type: 'diretriz',
    summary: 'Oferecer um ambiente seguro, acolhedor e estimulante para o desenvolvimento global do aluno.',
    details: [
      'Oferecer um ambiente seguro, acolhedor e estimulante para os alunos que frequentam o Programa de Integral.',
      'Proporcionar atividades lúdicas, recreativas e projetos que estimulem o desenvolvimento psicomotor, social e emocional.',
      'Oferecer atividades físicas que promovam o desenvolvimento motor e a saúde dos alunos (natação, judô, balé, dança, ginástica e futebol).',
      'Proporcionar oportunidade de aprender novas habilidades e desenvolver talentos em atividades específicas conforme preferências e interesses.',
      'Estimular criatividade e imaginação por meio de atividades artísticas e culturais (pintura, música, culinária, teatro e literatura).',
      'Fomentar espírito de equipe, cooperação e respeito mútuo por meio de atividades em grupo e jogos cooperativos.',
      'Desenvolver autonomia e responsabilidade, incentivando os alunos a tomarem decisões e a cuidarem de suas próprias coisas.',
      'Garantir refeições saudáveis no almoço com escolhas conscientes para o desenvolvimento físico e cognitivo.',
      'Promover saúde e bem-estar com práticas adequadas de higiene pessoal (lavagem das mãos e higienização bucal).',
      'Auxiliar na realização das lições de casa com assistência e orientação aos conteúdos pedagógicos, desenvolvendo autonomia no aprendizado.',
    ],
    tags: ['objetivos', 'metas', 'desenvolvimento', 'autonomia', 'acolhimento', 'integral'],
    order: 1,
  },
  {
    id: 'norma_direitos_legais',
    moduleId: 'normas_internas',
    moduleTitle: 'Módulo 1: Normas Internas e Rotina do Integral',
    sectionNumber: '1',
    sectionTitle: 'Direitos da Colaboradora / Estagiária',
    title: 'Dos Direitos Legais e Prerrogativas Funcionais',
    type: 'recomendado',
    summary: 'Garantias legais conforme o Termo de Compromisso de Estágio e normas do Colégio Crescer.',
    details: [
      'Ser apresentada pela Coordenação ou membro da equipe aos demais integrantes do Integral e receber informações sobre funcionamento e normas internas.',
      'Propor à Coordenação medidas que objetivem o aprimoramento da rotina, do roteiro de atividades, da conduta profissional e do trabalho com os alunos.',
      'Participar das discussões para a implementação do plano de trabalho, aplicação das atividades propostas no roteiro e no seu cumprimento.',
      'Comunicar à Coordenação do Integral as ocorrências que exijam providências superiores imediatas.',
      'Participar das reuniões de Formação promovidas pelo Integral para o seu contínuo aperfeiçoamento.',
      'Requisitar o material didático que julgar necessário ao desempenho de sua função, conforme roteiro definido e autorizado pela Coordenação.',
      'Organizar atividades extra roteiro somente com prévia autorização da Coordenação do Integral.',
      'Ocorrência de 01 (um) atraso mensal ao trabalho, que não ultrapasse 30 (trinta) minutos e seja devidamente justificado, por escrito, pela estagiária.',
    ],
    tags: ['direitos', 'estágio', 'coordenação', 'formação', 'material didático', 'atraso justificado'],
    order: 2,
  },
  {
    id: 'norma_deveres_gerais',
    moduleId: 'normas_internas',
    moduleTitle: 'Módulo 1: Normas Internas e Rotina do Integral',
    sectionNumber: '2',
    sectionTitle: 'Deveres Gerais das Monitoras',
    title: 'Dos Deveres Gerais, Pontualidade e Postura Ética',
    type: 'diretriz',
    summary: 'Compromissos indispensáveis de assiduidade, responsabilidade profissional e zelo institucional.',
    details: [
      'Manter assiduidade rigorosa, cumprindo o horário determinado pela Coordenação do Integral.',
      'Ser responsável pelo seu ponto eletrônico, registrando-o conforme horários determinados. Horários de trabalho não registrados serão descontados na folha de pagamento.',
      'Comunicar, na primeira oportunidade, à Coordenação a ocorrência de faltas e/ou atrasos, sendo obrigatória a justificativa.',
      'Não se ausentar antes do término do expediente sem prévia solicitação e autorização da Coordenação.',
      'Permanecer no seu local de trabalho, independentemente de estar com aluno ou não.',
      'Cooperar para a disciplina geral do estabelecimento e manter ambientes de trabalho organizados.',
      'Guardar sigilo e manter postura ética sobre assuntos profissionais ou particulares.',
      'Entregar em tempo hábil qualquer documento ou material solicitado pela Coordenação.',
      'Preservar e manter equipamentos e materiais de trabalho, comunicando defeitos, perdas ou quebras, responsabilizando-se pelo ressarcimento quando resultante de má utilização.',
      'Zelar pela economia e conservação do material que lhe for confiado à guarda ou uso.',
      'Agendar com a Coordenação, com antecedência de 07 (sete) dias, as ausências por motivos médicos de rotina (consultas, exames, etc.).',
    ],
    tags: ['deveres', 'assiduidade', 'ponto eletrônico', 'sigilo', 'ética', 'consultas médicas'],
    order: 3,
  },
  {
    id: 'norma_padrao_vestuario',
    moduleId: 'normas_internas',
    moduleTitle: 'Módulo 1: Normas Internas e Rotina do Integral',
    sectionNumber: '2.f & 2.g',
    sectionTitle: 'Padrão de Vestuário e Apresentação',
    title: 'Padrão Oficial de Vestuário, Cabelo e Acessórios',
    type: 'alerta',
    summary: 'Rigor nas normas de vestuário e proibição de acessórios que representem risco às crianças.',
    details: [
      'Cabelos compridos obrigatoriamente presos e com aparência de limpos.',
      'Unhas mantidas curtas para evitar arranhões nas crianças.',
      'NÃO usar acessórios como brincos, anéis, colares, correntes e pulseiras (o uso desses acessórios pode trazer riscos graves e acidentes durante o trabalho com as crianças).',
      'Uso de tênis diariamente (obrigatório calçado fechado e seguro).',
      'Calça jeans tradicional básica, legging ou moletom (NÃO será permitida calça agarrada e que limite a ação da funcionária).',
      'Bermudas discretas permitidas apenas com comprimento do joelho para baixo.',
      'NÃO usar peças do vestuário amarradas na cintura.',
      'Camiseta do uniforme do Integral: o uso da camiseta do Integral é estritamente obrigatório.',
      'A estagiária que estiver fora do padrão de vestuário acima informado NÃO poderá permanecer no ambiente de trabalho e terá sua ausência descontada em folha.',
    ],
    tags: ['vestuário', 'uniforme', 'tênis', 'cabelos presos', 'proibição de brincos', 'unhas curtas'],
    order: 4,
  },
  {
    id: 'norma_comunicacao_respeitosa',
    moduleId: 'normas_internas',
    moduleTitle: 'Módulo 1: Normas Internas e Rotina do Integral',
    sectionNumber: '2.h & 2.i',
    sectionTitle: 'Comunicação e Substituições',
    title: 'Comunicação Respeitosa e Disponibilidade para Substituições',
    type: 'alerta',
    summary: 'Comunicação apropriada com os alunos e responsabilidade compartilhada entre turmas.',
    details: [
      'É de extrema importância que a monitora mantenha uma comunicação respeitosa e apropriada com as crianças.',
      'Proibição absoluta do uso de linguagem vulgar, ofensiva, gírias, sarcasmo e expressões de baixo calão.',
      'Cabe às estagiárias atuarem em qualquer turma que lhes for designada pela coordenação, substituindo em outra turma quando necessário e responsabilizando-se pelos alunos e equipamentos.',
      'Cumprir e fazer cumprir, no âmbito de suas ações, todas as disposições das normas internas.',
    ],
    tags: ['comunicação', 'baixo calão', 'sarcasmo', 'substituição', 'respeito', 'linguagem'],
    order: 5,
  },
  {
    id: 'norma_proibicoes_gerais',
    moduleId: 'normas_internas',
    moduleTitle: 'Módulo 1: Normas Internas e Rotina do Integral',
    sectionNumber: '3.a-l',
    sectionTitle: 'Proibições Gerais',
    title: 'Proibições Gerais, Segurança dos Alunos e ECA',
    type: 'proibicao',
    summary: 'Condutas expressamente vedadas sob pena de sanções disciplinares e legais.',
    details: [
      'Receber no seu local de trabalho pessoas estranhas sem autorização prévia da Coordenação do Integral.',
      'Realizar atendimentos em regime particular nas dependências do Colégio Crescer.',
      'DEIXAR O ALUNO SOZINHO no local de trabalho quando estiver sob sua responsabilidade (tolerância zero).',
      'Fazer qualquer tipo de comentário inadequado perante os alunos, pais e visitantes.',
      'Recusar-se a substituir outro funcionário de sua área.',
      'Ausentar-se das salas ambientes com seus alunos sem prévia autorização da Coordenação do Integral.',
      'Fornecer endereços ou números de telefones de pais de alunos ou funcionários a pessoas estranhas sem prévia autorização da Coordenação.',
      'Não se vestir conforme os padrões estabelecidos pela Coordenação do Integral nas dependências da escola.',
      'Por qualquer motivo que seja, REGISTRAR O PONTO DE OUTRO FUNCIONÁRIO (falta grave com consequências imediatas).',
      'Descumprir qualquer direito da criança garantido pelo Estatuto da Criança e do Adolescente (ECA - Lei 8.069/1990).',
    ],
    tags: ['proibições', 'aluno sozinho', 'ponto de outro', 'eca', 'segurança', 'substituição'],
    order: 6,
  },
  {
    id: 'norma_proibicao_celular_conversas',
    moduleId: 'normas_internas',
    moduleTitle: 'Módulo 1: Normas Internas e Rotina do Integral',
    sectionNumber: '3.o, 3.p, 3.q',
    sectionTitle: 'Atenção Plena aos Alunos',
    title: 'Proibição Estrita de Celular e Conversas Paralelas em Horário de Atendimento',
    type: 'proibicao',
    summary: 'Atenção 100% voltada ao cuidado e fiscalização das crianças.',
    details: [
      'USO DO CELULAR NO HORÁRIO DE TRABALHO: É terminantemente proibido o uso de celular, seja nas dependências da escola ou em reuniões, exceto para comunicação interna quando o rádio não funcionar.',
      'PROIBIÇÃO DE CONVERSAS PARALELAS: Manter conversas individuais ou em grupo com outros funcionários dentro do horário de atendimento às crianças (no parque, refeitório, salas, quadras e pátios da escola) é expressamente proibido.',
      'LEMBRETE INSTITUCIONAL: Toda a atenção do funcionário deve ser voltada ao cuidado e fiscalização das crianças.',
      'Atender ligações que não sejam urgentes e efetuar ligações no telefone fixo somente mediante prévia autorização da Coordenação.',
      'Não se dirigir ao seu superior imediato, ou direto, de forma a figurar desrespeito.',
    ],
    tags: ['celular', 'conversas paralelas', 'parque', 'refeitório', 'atenção plena', 'rádio'],
    order: 7,
  },
  {
    id: 'norma_alimentacao_cuidados_salas',
    moduleId: 'normas_internas',
    moduleTitle: 'Módulo 1: Normas Internas e Rotina do Integral',
    sectionNumber: '3.j, 3.k, 3.r, 3.s',
    sectionTitle: 'Alimentos, Salas e Lanches',
    title: 'Regras de Alimentação, Organização das Salas e Saída Antecipada',
    type: 'proibicao',
    summary: 'Vedação ao compartilhamento de comida e organização das salas ambientes.',
    details: [
      'Alimentar-se com alimentos destinados aos alunos é proibido, exceto quando expressamente oferecidos pela Cozinha.',
      'COMPARTILHAR SEUS ALIMENTOS E DE TERCEIROS COM OS ALUNOS É ESTRITAMENTE PROIBIDO (risco grave de choque anafilático e quebra de regras nutricionais).',
      'DEIXAR AS SALAS DE USO EM ORDEM: carteiras alinhadas, sujeiras no lixo, equipamentos, ventiladores e ar condicionado desligados, luzes apagadas e janelas e portas fechadas.',
      'Entregar o lanche da geladeira ao aluno que for embora antes do intervalo.',
      'Cumprir com funções, horários e atividades determinadas pela Coordenação sem atrasos.',
    ],
    tags: ['alimentos', 'lanche', 'geladeira', 'fechamento de salas', 'ar condicionado', 'alergias'],
    order: 8,
  },
  {
    id: 'norma_deveres_especificos_monitoras',
    moduleId: 'normas_internas',
    moduleTitle: 'Módulo 1: Normas Internas e Rotina do Integral',
    sectionNumber: '4',
    sectionTitle: 'Cuidado e Supervisão Contínua',
    title: 'Deveres Específicos das Monitoras e Supervisão em Banheiros',
    type: 'diretriz',
    summary: 'Acolhimento afetivo e vigilância ativa em todos os ambientes escolares.',
    details: [
      'Acolher as crianças com demonstração de afetividade, respeito e carinho.',
      'Cuidar e orientar crianças em conformidade com a proposta pedagógica do Colégio Crescer.',
      'Promover o contato afetivo e harmonioso entre adultos e crianças.',
      'Orientar as crianças em suas atividades pedagógicas, recreativas, alimentares, higiênicas, fisiológicas e de repouso.',
      'Zelar pela guarda e conservação do material de consumo da escola.',
      'Auxiliar nas atividades de estimulação sensório-motora e lúdica.',
      'NÃO DEIXAR O ALUNO TRANSITAR pelas instalações da escola, PRINCIPALMENTE NOS AMBIENTES DOS BANHEIROS, sem a devida supervisão.',
      'Não se ausentar da sala de aula para resolução de quaisquer problemas no horário de atendimento sem autorização da Coordenação.',
      'Não guardar alimentos e nem se alimentar dentro da sala de aula durante o horário de atendimento das crianças.',
      'Respeitar e cumprir os procedimentos de entrega e recebimento das crianças (Procedimentos Gerais da escola).',
      'Sinalizar a leitura das mensagens no Grupo de WhatsApp, principalmente se for assunto vinculado à turma em que a monitora é responsável.',
    ],
    tags: ['supervisão', 'banheiros', 'afetividade', 'alimentação na sala', 'whatsapp', 'entrega de alunos'],
    order: 9,
  },
  {
    id: 'norma_cargos_lider_assistente_apoio',
    moduleId: 'normas_internas',
    moduleTitle: 'Módulo 1: Normas Internas e Rotina do Integral',
    sectionNumber: '5 & 6',
    sectionTitle: 'Hierarquia e Atribuições',
    title: 'Classificação das Monitoras: Assistente de Coordenação, Líder, Assistente e Apoio',
    type: 'diretriz',
    summary: 'Divisão clara de papéis e responsabilidades operacionais da equipe.',
    details: [
      'Assistente da Coordenação do Integral: responsável por auxiliar o Coordenador em suas tarefas, garantir funcionamento correto, coordenar atividades, participar de reuniões, controle de documentos e planejar roteiro semanal.',
      'Monitora Líder: responsável por coordenar e liderar a equipe de monitoras, garantindo que todas as atividades sejam realizadas conforme o planejado e que todas estejam alinhadas aos objetivos da formação.',
      'Monitora Assistente: responsável por auxiliar a Monitora Líder em suas tarefas diárias e garantir que tudo esteja funcionando perfeitamente.',
      'Monitora de Apoio: responsável por ajudar nas tarefas operacionais da formação (preparar materiais para atividades, organizar espaços e acompanhar a saída e chegada dos alunos).',
      'Coordenar o trabalho coletivo com foco no alinhamento contínuo com os objetivos da formação pedagógica.',
    ],
    tags: ['líder', 'assistente', 'apoio', 'atribuições', 'coordenação', 'organização'],
    order: 10,
  },
  {
    id: 'norma_fluxograma_ponto_radio',
    moduleId: 'normas_internas',
    moduleTitle: 'Módulo 1: Normas Internas e Rotina do Integral',
    sectionNumber: '8',
    sectionTitle: 'Rotina de Entrada e Comunicação',
    title: 'Fluxograma de Trabalho: Ponto, Armários e Rádio de Comunicação na Frequência 2',
    type: 'alerta',
    summary: 'Procedimento padrão obrigatório na chegada e saída do expediente.',
    details: [
      'Passo 1 • Pertences no Armário: Guardar seus pertences no armário destinado para seu uso antes de qualquer atividade. PROIBIDO deixar pertences espalhados por cima de mesas e locais de trabalho.',
      'Passo 2 • Ponto de Entrada: Registrar o ponto eletrônico de entrada após guardar os pertences.',
      'Passo 3 • Equipar-se com o Rádio: Pegar o rádio de comunicação destinado ao seu uso. Caso não o encontre no carregador, informar imediatamente a Coordenação.',
      'Passo 4 • Teste do Rádio: Verificar se o rádio está ligado, carregado, NA FREQUÊNCIA DO INTEGRAL (CANAL 2) e com o volume alto. Fazer o teste de todos esses itens.',
      'Passo 5 • Pasta e Mensagens: Munir-se da pasta de frequência e checar informações da turma no Grupo do Integral.',
      'Passo 6 • Acolhimento: Dirigir-se ao local de acolhimento das turmas no horário estabelecido em seu contrato.',
      'Passo 7 • Encerramento e Recarga do Rádio: No final do expediente, DESLIGAR O RÁDIO e colocá-lo para carregar. COM O RÁDIO LIGADO A BATERIA NÃO CARREGA E DANIFICA O EQUIPAMENTO. Verificar se o carregador está fixado (luz verde/laranja sinaliza carregamento correto).',
    ],
    tags: ['rádio frequência 2', 'fluxograma', 'carregador', 'armário', 'ponto de entrada', 'pasta'],
    order: 11,
  },
  {
    id: 'norma_procedimentos_refeitorio_refeicoes',
    moduleId: 'normas_internas',
    moduleTitle: 'Módulo 1: Normas Internas e Rotina do Integral',
    sectionNumber: '9',
    sectionTitle: 'Refeitório e Almoço',
    title: 'Procedimentos de Refeitório: Acomodação, Saladas, Sobremesa e Proibição de Bebedouro',
    type: 'recomendado',
    summary: 'Regras rigorosas para um almoço harmonioso, seguro e sem tumultos.',
    details: [
      'Cumprimento do Roteiro: Dedicar atenção ao horário de cada evento. Atrasos geram choques com outras turmas; antecipações somente com autorização da Coordenação.',
      'Horário UP (Reforço Escolar): Observar atentamente e enviar alunos convocados com 5 minutos de antecedência.',
      'Higienização das Mãos: Levar os alunos a fazer a higienização das mãos antes de cada refeição (almoço e lanche).',
      'Uso de Touca de Cabelo: A monitora deve vestir-se com a touca de proteção e manter os cabelos totalmente protegidos.',
      'Sequência de Mesas: Manter os alunos sentados e usar as mesas na sequência das turmas que já estão no refeitório.',
      'Acomodação nas Mesas: Seis alunos de cada lado para turmas do Mini ao Infantil II; cinco alunos de cada lado para turmas do 1º ao 6º ano. Essa mesma organização deve ser seguida no lanche.',
      'Serviço: Monitora serve a salada e a sobremesa para a sua turma. A sobremesa é servida em PORÇÃO ÚNICA.',
      'Observação Alimentar: Ficar atenta a como os alunos se alimentam. Ao notar recusa alimentar recorrente, informar à Coordenação Pedagógica.',
      'Objetos Alheios: Proibido levar brinquedos ou objetos alheios ao refeitório durante refeições.',
      'BEBEDOURO DO REFEITÓRIO: Orientar os alunos para NÃO TOMAR ÁGUA NO BEBEDOURO DO REFEITÓRIO durante o almoço. O bebedouro localiza-se no trajeto da fila do almoço; isso evita tumultos e empurra-empurra.',
      'Saída Organizada: Sair do refeitório em ordem, orientando os alunos a não correrem nem andarem apressadamente. Manter sentados e sair com toda a turma junta.',
    ],
    tags: ['refeitório', 'almoço', 'bebedouro proibido', 'touca', 'sobremesa única', 'horário up', 'mesas'],
    order: 12,
  },
  {
    id: 'norma_caderno_vai_e_volta',
    moduleId: 'normas_internas',
    moduleTitle: 'Módulo 1: Normas Internas e Rotina do Integral',
    sectionNumber: '9.l',
    sectionTitle: 'Comunicação com as Famílias',
    title: 'Caderno Vai e Volta e Lançamento de Frequência',
    type: 'diretriz',
    summary: 'Procedimento formal para comunicados institucionais com as famílias.',
    details: [
      'Iniciar o cumprimento do Roteiro de Atividades com segurança e domínio da ordem do dia.',
      'Fazer a chamada e registrar a frequência pontualmente no aplicativo/pasta.',
      'Verificar o Caderno Vai e Volta de todos os alunos diariamente.',
      'Encaminhar comunicados dos pais imediatamente para a Coordenação do Integral.',
      'NÃO ESCREVER no Caderno Vai e Volta sem prévia autorização da Coordenação do Integral.',
      'Colar comunicados no Caderno Vai e Volta com rigor estético: sem rasuras e com impresso perfeitamente alinhado na folha.',
      'Na impossibilidade de cumprir atividades propostas por qualquer motivo, comunicar a Coordenação.',
    ],
    tags: ['vai e volta', 'chamada', 'comunicados', 'estética visual', 'coordenação', 'famílias'],
    order: 13,
  },
  {
    id: 'norma_acolhimento_por_faixa_etaria',
    moduleId: 'normas_internas',
    moduleTitle: 'Módulo 1: Normas Internas e Rotina do Integral',
    sectionNumber: '10',
    sectionTitle: 'Acolhimento e Mochilas',
    title: 'Procedimentos de Acolhimento das Turmas e Soninho (Mini ao 6º Ano)',
    type: 'diretriz',
    summary: 'Fluxos específicos para busca, mochilas e preparação de caminhas por faixa etária.',
    details: [
      'Mini ao Infantil 2: Buscar alunos nas salas de aula acompanhando o deslocamento; conduzir à sala do Integral de forma tranquila; organizá-los para saída ao refeitório; dispor mochilas em fileiras para fácil localização; enquanto a monitora líder oferece o almoço, a monitora de apoio deve preparar cuidadosamente as caminhas para o soninho (dispor lençóis, cobertores e travesseiros de forma acolhedora e segura).',
      '1º Ano: Buscar alunos nas salas com segurança; conduzi-los ao local designado para deixar mochilas em ordem; formar fila organizada para o refeitório.',
      '2º e 3º Ano: Aguardar alunos no ponto de encontro designado para recebê-los; organizar mochilas no local sem confusão; organizar fila para entrada no refeitório.',
      '4º ao 6º Ano: Acolher nas salas específicas destinadas ao Integral; conduzir ao refeitório conforme cronograma de horários para evitar aglomerações; fila ordenada na sequência correta.',
    ],
    tags: ['acolhimento', 'soninho', 'caminhas', 'mochilas em fileiras', 'mini maternal', 'infantil'],
    order: 14,
  },
  {
    id: 'norma_cuidados_bebes_mini_maternal',
    moduleId: 'normas_internas',
    moduleTitle: 'Módulo 1: Normas Internas e Rotina do Integral',
    sectionNumber: '11.a',
    sectionTitle: 'Educação Infantil Inicial',
    title: 'Orientações Específicas para Mini Maternal e Maternal: Higiene, Fraldas e Mamadeiras',
    type: 'alerta',
    summary: 'Protocolo sanitário e de proteção física aos bebês e crianças bem pequenas.',
    details: [
      'Verificação Inicial de Saúde: Ao receber a criança, realizar verificação inicial. Caso seja observado algum hematoma, machucado ou marca, informar imediatamente à Coordenação.',
      'Kit de Higiene Individual: Usar estritamente o kit higiene de cada aluno e JAMAIS compartilhar kits (pente/escova de cabelo, pasta de dente, escova de dente, lenço umedecido e roupa de cama).',
      'Lavagem de Mãos: Lavar as mãos das crianças antes de cada refeição (almoço e lanche da tarde).',
      'Troca de Fraldas com Luvas: Trocar as crianças e fazer a higienização obrigatoriamente com o uso de LUVAS DESCARTÁVEIS.',
      'Mamadeiras: Usar água filtrada para preparar mamadeiras na hora da mamada e aquecê-las antes de oferecer às crianças.',
      'Conferência na Saída: Verificar a fralda da criança antes de ela ir embora e, se necessário, realizar a troca.',
      'Reposição: Informar à Coordenação quando os descartáveis das crianças estiverem no fim para solicitação de reposição aos pais.',
    ],
    tags: ['maternal', 'fraldas', 'luvas descartáveis', 'mamadeiras', 'kit higiene', 'hematomas'],
    order: 15,
  },
  {
    id: 'norma_oficinas_teens_vestuario_lego',
    moduleId: 'normas_internas',
    moduleTitle: 'Módulo 1: Normas Internas e Rotina do Integral',
    sectionNumber: '11.b',
    sectionTitle: 'Fundamental Anos Iniciais e Finais',
    title: 'Orientações para o 2º ao 6º Ano (Teens), Oficinas e Atividades com Lego',
    type: 'recomendado',
    summary: 'Diretrizes para alunos maiores, vestimentas para oficinas e mediação de projetos.',
    details: [
      'Controle Inicial: Verificar quantidade de crianças presentes, saídas antecipadas e/ou faltas, organizando-as em grupos.',
      'Fichas Preenchidas: Ao chegar à sala, solicitar o retorno das fichas preenchidas a fim de analisar comunicações de participação na academia ou eventos.',
      'Efetuar chamada rigorosa dos alunos.',
      'Vestimentas Específicas: Garantir roupas adequadas para práticas como balé, dança e judô, mantendo a motivação dos alunos.',
      'Calçados nas Atividades Físicas: Assegurar uso de tênis e shorts confortáveis. RESSALTA-SE A PROIBIÇÃO DE PERMANECER DESCALÇO, UTILIZAR CHINELOS OU MEIAS durante as atividades físicas para preservar a integridade física.',
      'Oficina de Lego: Promover intencionalidade pedagógica e construções ligadas ao tema da semana ou temas de exploração coletiva; acolher ideias das crianças promovendo o desenvolvimento global.',
      'Tarefas de Casa: Verificar tarefas do dia no quadro; salas divididas devem ter representantes anotando tarefas; apoio em pesquisas com computadores; equilíbrio com bom senso sem sobrecarregar alunos ausentes.',
    ],
    tags: ['teens', 'lego', 'proibido descalço', 'tênis obrigatório', 'balé', 'judô', 'tarefas'],
    order: 16,
  },
  {
    id: 'norma_regras_parque_parcao',
    moduleId: 'normas_internas',
    moduleTitle: 'Módulo 1: Normas Internas e Rotina do Integral',
    sectionNumber: '14 & Anexo Parque',
    sectionTitle: 'Parque e Brinquedão',
    title: 'Orientações Oficiais para Uso do Parque (Parcão): Segurança e Postura Ativa',
    type: 'alerta',
    summary: 'Regras diárias de preservação dos brinquedos e vigilância preventiva ativa das monitoras.',
    details: [
      'ESCORREGADOR: É proibido subir pelo escorregador. A descida deve ser sempre feita sentado, nunca em pé.',
      'PULA-PULA: Apenas duas crianças podem brincar simultaneamente.',
      'BRINQUEDÃO: Equilibrar a quantidade de crianças entre o brinquedão e a área inferior (metade em cima e metade embaixo). O número total de crianças NÃO DEVE EXCEDER 10 ALUNOS.',
      'PISCINA DE BOLINHAS: Os alunos não podem retirar as bolinhas da piscina, especialmente levando-as para outras áreas do brinquedão.',
      'TELAS E ESPUMAS DE PROTEÇÃO: Prestar atenção máxima às telas e espumas. Não permitir que crianças danifiquem as espumas ou fiquem penduradas nas telas.',
      'USO DE CELULAR NO PARQUE: É ESTRITAMENTE PROIBIDO O USO DE CELULAR NO PARQUE (foco visual 100% nas crianças).',
      'BOLA DE FUTEBOL: A bola deve ser utilizada apenas no campinho designado. Não permitir que seja levada para o brinquedão ou outros locais.',
      'POSTURA DA MONITORA NO PARQUE: É fundamental manter um olhar atento e CAMINHAR PELO PARQUE, EVITANDO PERMANECER SENTADAS. Estar sempre preparadas para prevenir acidentes. Muitos desgastes e quedas são evitados com nossa orientação e supervisão ativa.',
    ],
    tags: ['parque', 'parcão', 'brinquedão', 'escorregador', 'pula-pula', 'celular proibido', 'monitora em pé'],
    order: 17,
  },
  {
    id: 'norma_regras_culinaria',
    moduleId: 'normas_internas',
    moduleTitle: 'Módulo 1: Normas Internas e Rotina do Integral',
    sectionNumber: '13',
    sectionTitle: 'Oficina de Culinária',
    title: 'Normas de Segurança Alimentar e Boas Práticas na Culinária',
    type: 'recomendado',
    summary: 'Procedimentos higiênico-sanitários e respeito às orientações da Nutricionista.',
    details: [
      'Higiene Pessoal: Facilitadora com mãos limpas, unhas curtas, uso de touca/rede de cabelo, avental e luvas descartáveis para evitar contaminação.',
      'Limpeza do Espaço: Espaço limpo e organizado antes de iniciar; utensílios, bancadas e superfícies devidamente higienizados.',
      'Manipulação de Alimentos: Cuidado na manipulação de alimentos crus, evitando contato direto com alimentos prontos para impedir contaminação cruzada.',
      'Respeito às Receitas: Seguir rigorosamente as receitas e porções fornecidas pela Nutricionista (quantidades, ordem de preparo e técnicas).',
      'Proibição de Desperdício: Utilizar ingredientes de forma consciente, evitando descartes desnecessários e buscando reaproveitamento consciente.',
      'Segurança Alimentar: Pratos armazenados em recipientes adequados, refrigeração de perecíveis e cocção/aquecimento seguro dos alimentos.',
      'Limpeza Pós-Preparo: Lavar todos os utensílios e equipamentos, descarte correto do lixo e organização dos materiais utilizados.',
    ],
    tags: ['culinária', 'nutricionista', 'segurança alimentar', 'higiene', 'touca', 'contaminação cruzada'],
    order: 18,
  },
  {
    id: 'norma_licao_de_casa_por_ano',
    moduleId: 'normas_internas',
    moduleTitle: 'Módulo 1: Normas Internas e Rotina do Integral',
    sectionNumber: '15',
    sectionTitle: 'Apoio Pedagógico',
    title: 'Diretrizes Oficiais de Lição de Casa por Faixa Etária (Infantil 2 ao 6º Ano)',
    type: 'diretriz',
    summary: 'Autonomia infantil, papel da monitora como facilitadora e vedação à correção.',
    details: [
      'Infantil 2: Lição realizada 1 vez por semana a partir do 2º semestre; crianças sentadas à mesa com a monitora ao lado orientando a maneira correta; folhinha mantida limpa, caprichada e com nome verificado.',
      '1º Ano: Conforme orientações do Caderno Vai e Volta e folha E1 na pasta da turma; alunos sentados nas carteiras e monitoras circulando; foco em orientar o raciocínio independente (não dar respostas); A CORREÇÃO FICA A CARGO DA PROFESSORA DA TURMA (as monitoras NÃO devem corrigir tarefas); tarefas de pesquisa com dados pessoais devem ser feitas em casa com a família.',
      '2º Ano: Baseado no Vai e Volta e E1; monitoras circulam esclarecendo dúvidas sem fornecer respostas; correção é da professora; DURANTE A SEMANA DE PROVAS NÃO HÁ LIÇÃO DE CASA: o tempo é dedicado ao estudo para a prova do dia seguinte.',
      '3º ao 6º Ano: Baseado no Vai e Volta e E1; alunos sentados em suas carteiras; permitido o uso da lousa para explicações e orientações coletivas; monitoras NÃO corrigem lições; pesquisas com a família; LIÇÕES SUSPENSAS NA SEMANA DE PROVAS para dedicação aos estudos da disciplina da prova do dia seguinte.',
      'Responsabilidade do Integral: Acompanhar e auxiliar nas lições do dia; não nos cabe assumir responsabilidade por lições atrasadas em dias de ausência do aluno; bom senso para evitar sobrecarga.',
    ],
    tags: ['lição de casa', 'e1', 'vai e volta', 'monitora não corrige', 'semana de provas', 'lousa'],
    order: 19,
  },
  {
    id: 'norma_penalidades_estagio',
    moduleId: 'normas_internas',
    moduleTitle: 'Módulo 1: Normas Internas e Rotina do Integral',
    sectionNumber: '16',
    sectionTitle: 'Regime Disciplinar',
    title: 'Das Penalidades por Descumprimento das Normas',
    type: 'proibicao',
    summary: 'Graduação das sanções disciplinares aplicáveis em caso de infração funcional.',
    details: [
      'O não cumprimento das normas e regras estabelecidas poderá acarretar sanções disciplinares, sem prejuízo das obrigações trabalhistas, civis e criminais decorrentes dos atos praticados pela colaboradora/estagiária:',
      'a. Advertência verbal;',
      'b. Advertência por escrito;',
      'c. Suspensão temporária das atividades de estágio;',
      'd. Rescisão do contrato de estágio (inclusive por falta grave / justa causa).',
      'A colaboradora declara que leu e concorda com as disposições do documento, comprometendo-se a cumpri-las integralmente.',
    ],
    tags: ['penalidades', 'advertência', 'suspensão', 'rescisão', 'justa causa', 'disciplina'],
    order: 20,
  },

  // ==========================================
  // MÓDULO 2: ACADEMIA, TRANSPORTE E LOCAIS PARCEIROS
  // ==========================================
  {
    id: 'norma_academia_deslocamento_portaria',
    moduleId: 'academia_transporte',
    moduleTitle: 'Módulo 2: Academia, Transporte e Locais Parceiros',
    sectionNumber: '12.a-d',
    sectionTitle: 'Deslocamento Interno e Embarque',
    title: 'Deslocamento Interno para a Portaria e Regras de Embarque por Bloco',
    type: 'alerta',
    summary: 'Rotas de circulação obrigatórias para Blocos B e C e controle na Portaria.',
    details: [
      'Conferência de Pertences: Antes de embarcar, verificar se os alunos pegaram todos os seus pertences e, especialmente, suas GARRAFAS DE ÁGUA para hidratação essencial.',
      'Alunos do Bloco C: Deslocar-se com a turma para a Portaria pelo ACESSO DO PARCÃO.',
      'Alunos do Bloco B: Deslocar-se com a turma pela RAMPA DA PORTARIA.',
      'PROIBIÇÃO DE ACESSO: É ESTRITAMENTE PROIBIDO o deslocamento das turmas do Bloco B pelo rol de entrada da Secretaria.',
      'Espera: Aguardar o embarque no corredor lateral da rampa da Portaria em fila organizada.',
      'Presença do Condutor: Embarcar somente mediante autorização expressa e COM A PRESENÇA DO CONDUTOR do transporte.',
    ],
    tags: ['academia', 'bloco b', 'bloco c', 'parcão', 'rampa da portaria', 'secretaria proibida', 'condutor'],
    order: 21,
  },
  {
    id: 'norma_academia_10_regras_comportamento',
    moduleId: 'academia_transporte',
    moduleTitle: 'Módulo 2: Academia, Transporte e Locais Parceiros',
    sectionNumber: '12.e & Anexo Academia',
    sectionTitle: 'Conduta na Academia',
    title: 'As 10 Regras Obrigatórias de Comportamento na Academia (Leitura em Todos os Embarques)',
    type: 'proibicao',
    summary: 'Instruções lidas pelas monitoras antes de cada deslocamento para a academia.',
    details: [
      'A monitora DEVE LER AS ORIENTAÇÕES DE COMPORTAMENTO NA ACADEMIA EM TODOS OS EMBARQUES:',
      '1. NÃO GRITAR;',
      '2. NÃO CORRER;',
      '3. NÃO BRINCAR NOS BEBEDOUROS E NEM TOMAR ÁGUA DE CONCHINHA COM AS MÃOS;',
      '4. FAZER O MÁXIMO DE SILÊNCIO POSSÍVEL;',
      '5. NÃO SENTAR NAS VIAS DE PASSAGEM (meio da recepção, escada principal e corredores);',
      '6. SE COMPORTAR E RESPEITAR OS PROFESSORES DURANTE AS AULAS;',
      '7. AO TÉRMINO DA AULA, DE MANEIRA NENHUMA, SAIR DO PORTÃO DA RECEPÇÃO, NEM EMBARCAR, SEM A AUTORIZAÇÃO DA MONITORA;',
      '8. NÃO ESQUECER NENHUM PERTENCE NA ACADEMIA;',
      '9. NÃO CORRER PARA REALIZAR O EMBARQUE E DESEMBARQUE;',
      '10. NÃO IR AO TRANSPORTE SEM A AUTORIZAÇÃO DA RESPONSÁVEL PELA TURMA.',
    ],
    tags: ['10 regras', 'academia', 'bebedouro conchinha', 'não gritar', 'silêncio', 'escada', 'portão'],
    order: 22,
  },
  {
    id: 'norma_academia_retorno_portao_calcada',
    moduleId: 'academia_transporte',
    moduleTitle: 'Módulo 2: Academia, Transporte e Locais Parceiros',
    sectionNumber: '12.f, 12.g & Anexo Academia',
    sectionTitle: 'Segurança nos Portões e Retorno',
    title: 'Segurança no Retorno ao Colégio: Monitora como Última a Entrar e Proibição na Calçada',
    type: 'alerta',
    summary: 'Blindagem de segurança para não deixar nenhum aluno para trás.',
    details: [
      'Embarcar para retorno à escola estritamente mediante autorização da equipe e condutor.',
      'MONITORA DEVE SER A ÚLTIMA A ENTRAR pelo portão da academia na ida e do colégio na volta.',
      'Verificação Completa: Ao chegar na escola, a monitora deve verificar se todos os alunos estão com seus pertences e assegurar que ninguém tenha ficado para trás.',
      'RISCO GRAVE NA CALÇADA: NUNCA é permitido entrar e deixar aluno na calçada, pois isso coloca a segurança física do aluno em risco gravíssimo perante o trânsito.',
      'A cooperação de todas é essencial para manter um ambiente seguro e saudável.',
    ],
    tags: ['retorno', 'última a entrar', 'calçada proibida', 'pertences', 'segurança no portão'],
    order: 23,
  },
  {
    id: 'norma_academia_uniforme_proibicao_chinelos',
    moduleId: 'academia_transporte',
    moduleTitle: 'Módulo 2: Academia, Transporte e Locais Parceiros',
    sectionNumber: '12.h',
    sectionTitle: 'Troca de Calçado e Uniforme',
    title: 'Troca Obrigatória de Uniforme da Academia e Proibição de Chinelos no Integral',
    type: 'proibicao',
    summary: 'Uso obrigatório de tênis no colégio logo após o retorno das aulas da academia.',
    details: [
      'O aluno NÃO PODE realizar a rotina do Integral vestindo o uniforme das modalidades praticadas na academia, seja antes ou depois das aulas.',
      'É ESTRITAMENTE PROIBIDO o uso de chinelos, sandálias abertas ou andar descalço durante a rotina do Integral.',
      'TROCA POR TÊNIS OBRIGATÓRIA: Após participar das aulas práticas da academia (como natação), é OBRIGATÓRIO que o aluno troque seus chinelos por tênis.',
      'Garantir a preservação da integridade física dos alunos em relação ao piso do colégio e atividades de recreação.',
    ],
    tags: ['proibição de chinelo', 'tênis obrigatório', 'uniforme da academia', 'troca de roupa', 'piso'],
    order: 24,
  },

  // ==========================================
  // MÓDULO 3: GUIA DE ABORDAGEM SENSÍVEL E RESPEITOSA (Coordenação Fernando Veiga)
  // ==========================================
  {
    id: 'norma_sensivel_apresentacao',
    moduleId: 'guia_sensivel',
    moduleTitle: 'Módulo 3: Guia de Abordagem Sensível e Respeitosa',
    sectionNumber: 'Apresentação',
    sectionTitle: 'Carta da Coordenação Pedagógica',
    title: 'Apresentação do Guia de Abordagem Sensível e Respeitosa (Coord. Fernando Veiga)',
    type: 'diretriz',
    summary: 'Princípios institucionais de cultivo da confiança e desenvolvimento integral saudável.',
    details: [
      'Prezadas Monitoras do Programa Integral: Apresentamos o "Guia de Abordagem Sensível e Respeitosa no Trato com Alunos do Programa Integral". Este guia é um recurso essencial para promover interações positivas e enriquecedoras com nossos alunos.',
      'Ambiente Positivo: O guia destaca a importância de um ambiente escolar que promova não apenas o aprendizado, mas também o crescimento emocional e a socialização saudável de nossas crianças.',
      'Nosso objetivo é fornecer orientações práticas para cultivar relacionamentos de confiança e criar um espaço onde cada criança possa prosperar.',
      'Agradecemos por sua dedicação em seguir essas diretrizes, desempenhando um papel vital na promoção do crescimento saudável em nosso convívio diário com as crianças.',
    ],
    tags: ['fernando veiga', 'apresentação', 'confiança', 'crescimento emocional', 'socialização'],
    order: 25,
  },
  {
    id: 'norma_sensivel_nao_gritar',
    moduleId: 'guia_sensivel',
    moduleTitle: 'Módulo 3: Guia de Abordagem Sensível e Respeitosa',
    sectionNumber: '7.a / 1',
    sectionTitle: 'Comunicação Assertiva',
    title: '1. Não Gritar: Comunicação Calma e Firmeza Gentil',
    type: 'proibicao',
    summary: 'Gritar gera ansiedade e medo; a comunicação deve ser serena e assertiva.',
    details: [
      'Gritar para disciplinar ou comunicar-se com os alunos pode criar um ambiente de medo e ansiedade.',
      'O grito afeta negativamente a autoestima das crianças, dificulta a comunicação aberta e impede a construção de um relacionamento saudável entre aluno e monitora.',
      'Em vez de gritar, é comprovadamente mais eficaz utilizar uma COMUNICAÇÃO CALMA E ASSERTIVA para resolver problemas e orientar o comportamento dos alunos.',
    ],
    tags: ['não gritar', 'comunicação assertiva', 'autoestima', 'voz calma', 'medo', 'ansiedade'],
    order: 26,
  },
  {
    id: 'norma_sensivel_nao_pegar_com_forca',
    moduleId: 'guia_sensivel',
    moduleTitle: 'Módulo 3: Guia de Abordagem Sensível e Respeitosa',
    sectionNumber: '7.b / 2',
    sectionTitle: 'Espaço Pessoal da Criança',
    title: '2. Não Pegar as Crianças Pequenas com Força: Respeito ao Espaço Corporal',
    type: 'proibicao',
    summary: 'Aproximação não invasiva e respeito à integridade física infantil.',
    details: [
      'Pegar uma criança com força pode ser percebido como uma ameaça ou invasão do seu espaço pessoal.',
      'Essa conduta pode gerar desconforto físico, resistência comportamental e até mesmo trauma emocional.',
      'É fundamental respeitar o espaço pessoal das crianças e utilizar abordagens não invasivas:',
      'Abordagem correta: AGACHAR-SE PARA FICAR AO NÍVEL DA CRIANÇA, oferecendo a mão para que ela possa segurar, caso seja necessário conduzi-la.',
    ],
    tags: ['não pegar com força', 'agachar', 'oferecer a mão', 'espaço pessoal', 'trauma emocional'],
    order: 27,
  },
  {
    id: 'norma_sensivel_nao_puxar_pelos_bracos',
    moduleId: 'guia_sensivel',
    moduleTitle: 'Módulo 3: Guia de Abordagem Sensível e Respeitosa',
    sectionNumber: '7.c / 3',
    sectionTitle: 'Integridade Física',
    title: '3. Não Puxar as Crianças Pequenas pelos Braços: Abordagem Gentil e Diálogo',
    type: 'proibicao',
    summary: 'Puxar pelos braços é ato agressivo e causa ferimentos físicos e emocionais.',
    details: [
      'Puxar uma criança pelos braços pode causar sério desconforto físico e emocional, podendo inclusive resultar em ferimentos ou luxações articulares.',
      'Essa ação é percebida pela criança como agressiva, o que destrói a relação de confiança entre aluno e monitora.',
      'Conduta recomendada: As monitoras devem AGACHAR AO NÍVEL DA CRIANÇA, EXPLICAR O QUE PRECISA SER FEITO E INCENTIVAR A COOPERAÇÃO através de uma abordagem gentil.',
    ],
    tags: ['não puxar', 'braços', 'ferimentos', 'agressividade', 'agachar ao nível', 'cooperação'],
    order: 28,
  },
  {
    id: 'norma_sensivel_nao_agir_com_aspereza',
    moduleId: 'guia_sensivel',
    moduleTitle: 'Módulo 3: Guia de Abordagem Sensível e Respeitosa',
    sectionNumber: '7.d / 4',
    sectionTitle: 'Empatia e Acolhimento',
    title: '4. Não Agir com Aspereza: Empatia, Compreensão e Segurança Psicológica',
    type: 'alerta',
    summary: 'Crianças aprendem pela gentileza e pelo respeito, nunca pela rispidez.',
    details: [
      'A aspereza na abordagem aos alunos pode desencadear sentimentos de ansiedade profunda, desconfiança e sensação de desrespeito.',
      'As crianças aprendem de maneira muito mais eficaz quando são tratadas com genuína empatia e compreensão.',
      'Utilizar uma abordagem gentil e respeitosa estabelece um ambiente seguro onde os alunos se sentem confortáveis para expressar suas dúvidas e preocupações.',
    ],
    tags: ['não agir com aspereza', 'gentileza', 'empatia', 'compreensão', 'segurança'],
    order: 29,
  },
  {
    id: 'norma_sensivel_ter_paciencia',
    moduleId: 'guia_sensivel',
    moduleTitle: 'Módulo 3: Guia de Abordagem Sensível e Respeitosa',
    sectionNumber: '7.e / 5',
    sectionTitle: 'Ritmos de Aprendizagem',
    title: '5. Ter Paciência: Respeito aos Diferentes Ritmos de Desenvolvimento',
    type: 'recomendado',
    summary: 'Compreender o tempo de maturação da criança e evitar frustrações recíprocas.',
    details: [
      'A paciência é princípio fundamental no ambiente educacional, pois as crianças possuem ritmos de aprendizado diferentes e necessitam de tempo para compreender e internalizar conceitos.',
      'Perder a paciência leva à frustração tanto para os alunos quanto para as monitoras, prejudicando o processo de interação e o relacionamento interpessoal.',
      'Demonstrar paciência ajuda a criar um ambiente de apoio recíproco, onde os alunos sentem-se confortáveis para realizar as atividades propostas e pedir ajuda sempre que precisarem.',
    ],
    tags: ['paciência', 'ritmos diferentes', 'ambiente de apoio', 'frustração', 'desenvolvimento'],
    order: 30,
  },
  {
    id: 'norma_sensivel_nao_ameacar',
    moduleId: 'guia_sensivel',
    moduleTitle: 'Módulo 3: Guia de Abordagem Sensível e Respeitosa',
    sectionNumber: '7.f / 6',
    sectionTitle: 'Motivação Intrínseca',
    title: '6. Não Ameaçar: Motivação Positiva e Comunicação de Expectativas',
    type: 'proibicao',
    summary: 'Ameaças geram inibição e superficialidade; motivar pelas expectativas positivas.',
    details: [
      'O uso de ameaças cria um ambiente de medo e ansiedade, prejudicando severamente a autoconfiança das crianças.',
      'Ameaçar inibe a disposição da criança para participar ativamente das atividades propostas; o medo conduz a interações superficiais e desinteresse gradual.',
      'Em vez de ameaçar, é muito mais construtivo comunicar as expectativas de comportamento de maneira positiva.',
      'Focar em recompensas intrínsecas, reconhecimento do esforço e incentivo sincero para motivar os alunos.',
    ],
    tags: ['não ameaçar', 'motivação positiva', 'autoconfiança', 'medo', 'recompensas intrínsecas'],
    order: 31,
  },
  {
    id: 'norma_sensivel_mediacao_conflitos',
    moduleId: 'guia_sensivel',
    moduleTitle: 'Módulo 3: Guia de Abordagem Sensível e Respeitosa',
    sectionNumber: '7.g / 7',
    sectionTitle: 'Resolução de Conflitos',
    title: '7. Mediação Construtiva de Conflitos em 3 Passos (Protocolo Oficial)',
    type: 'recomendado',
    summary: 'Transformar conflitos em momentos ricos de aprendizado e convivência cidadã.',
    details: [
      'Conflitos são oportunidades de aprendizado. Como monitoras, vocês têm um papel primordial na mediação construtiva entre os alunos:',
      '1. Abordagem Imparcial: Ouça com calma ambas as partes envolvidas para compreender a situação de forma equilibrada e sem julgamentos prévios.',
      '2. Comunicação Ativa: Incentive os alunos a expressarem seus sentimentos, necessidades e perspectivas de maneira respeitosa, ajudando-os a colocar em palavras o que sentem.',
      '3. Soluções Colaborativas: Ajude os alunos a encontrarem soluções juntos, promovendo a resolução pacífica, o pedido de desculpas sincero e a restauração do vínculo.',
      'Conclusão da Coordenação: "Ao adotar essas práticas positivas no trato com os alunos do Integral, as monitoras constroem relacionamentos de confiança, criam um ambiente saudável e promovem o desenvolvimento completo das nossas crianças." (Fernando Veiga - Coordenador Integral).',
    ],
    tags: ['mediação de conflitos', '3 passos', 'imparcialidade', 'comunicação ativa', 'soluções colaborativas', 'fernando veiga'],
    order: 32,
  },
];
